Repository MaFeLP/discord_bots, pull requests merged in 2022-01, with the labels that each got.

#13 Editorconfig
  .editorconfig
Labels: enhancement

#12 Features/logging
  .gitignore
  Cargo.lock
  Cargo.toml
  build.rs
  src/config.rs
  src/kaenguru.rs
  src/logger/custom/filter.rs
  src/logger/custom/mod.rs
  src/logger/custom/trigger.rs
  src/logger/mod.rs
  src/main.rs
  src/replies.rs
  src/xd.rs
Labels: enhancement, dependencies

#14 Switch from lazy_static to once_cell for lazy evaluation
  Cargo.lock
  Cargo.toml
  src/common.rs
  src/config.rs
  src/kaenguru/euro_to_mark.rs
  src/logger/custom/trigger.rs
  src/main.rs
  src/replies.rs
Labels: enhancement, dependencies, rust
